name: ci

on:
  push:
    tags:        
      - "*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: make build

    - name: Run tests
      run: make test

    - name: Package
      run: make package

    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          ./.build/apple/Products/Release/_PRODUCT/swiftshield.zip
        generate_release_notes: true
        draft: false
        prerelease: false